module Reporting

using Printf
using Dates
using JSON
using Statistics: mean
using ..Core

export generate_text_report, export_scaling_dat

function generate_text_report(results, output_dir)
    filename = joinpath(output_dir, "summary.txt")
    open(filename, "w") do io
        println(io, "================================================================")
        println(io, "             GPU HEALTH CERTIFICATE - $(results["timestamp"])")
        println(io, "================================================================")
        println(io, "")
        println(io, "[1. NODE ENVIRONMENT]")
        
        metadata = get(results, "metadata", Dict())
        println(io, "  Hostname:      $(get(metadata, "hostname", "unknown"))")
        println(io, "  Julia:         v$(VERSION)")
        
        if get(results, "cuda_functional", false)
            println(io, "  CUDA Runtime:  $(get(metadata, "cuda_runtime", "unknown"))")
            println(io, "  CUDA Driver:   $(get(metadata, "cuda_driver", "unknown"))")
        else
            println(io, "  CUDA:          [WARNING] NOT FUNCTIONAL")
        end
        
        println(io, "")
        println(io, "[2. HARDWARE CAPABILITY]")
        benchmarks = get(results, "benchmarks", Dict())
        if haskey(benchmarks, "sysinfo")
            si = benchmarks["sysinfo"]
            if !haskey(si, "error")
                # CPU / System
                if haskey(si, "cpu_model")
                    println(io, "  CPU Model:     $(si["cpu_model"])")
                end
                if haskey(si, "cpu_arch")
                    println(io, "  CPU Arch:      $(si["cpu_arch"])")
                end
                if haskey(si, "cpu_threads")
                    println(io, "  CPU Threads:   $(si["cpu_threads"])")
                end
                if haskey(si, "ram_total")
                    println(io, "  Total RAM:     $(si["ram_total"])")
                end
                # GPU
                println(io, "  GPU Model:     $(get(si, "gpu_name", "unknown"))")
                println(io, "  Compute Cap:   $(get(si, "compute_capability", "unknown"))")
                println(io, "  Total VRAM:    $(get(si, "vram_total", "unknown"))")
                println(io, "  GPU UUID:      $(get(si, "gpu_uuid", "unknown"))")
                if haskey(si, "pci_bus_id")
                    println(io, "  PCI Bus ID:    $(si["pci_bus_id"])")
                end
                if haskey(si, "gpu_count") && si["gpu_count"] > 1
                    println(io, "  GPU Count:     $(si["gpu_count"])")
                end
            else
                println(io, "  Status:        Failed to collect capability info.")
            end
        end

        println(io, "")
        println(io, "[3. PERFORMANCE RESULTS]")
        
        if haskey(benchmarks, "matmul")
            m = benchmarks["matmul"]
            if !haskey(m, "error")
                @printf(io, "  Raw Compute:   %.2f TFLOPS (FP32)\n", get(m, "tflops", 0.0))
            end
        end

        if haskey(benchmarks, "tensorcore")
            t = benchmarks["tensorcore"]
            if !haskey(t, "error")
                @printf(io, "  Tensor Cores:  %.2f TFLOPS (Mixed Prec)\n", get(t, "tflops", 0.0))
            end
        end

        if haskey(benchmarks, "scaling")
            s = benchmarks["scaling"]
            @printf(io, "  Peak Compute:  %.2f TFLOPS (GPU Scaling)\n", get(s, "peak_gpu_tflops", 0.0))
        end

        if haskey(benchmarks, "gpuinspector")
            r = benchmarks["gpuinspector"]
            if !haskey(r, "error")
                if haskey(r, "memory_bandwidth")
                    @printf(io, "  Memory BW:     %.2f GiB/s\n", get(r, "memory_bandwidth", 0.0))
                end
                if haskey(r, "peak_power")
                    @printf(io, "  Peak Power:    %.1f W\n", get(r, "peak_power", 0.0))
                end
            end
        end
        println(io, "")
        println(io, "================================================================")
        println(io, "Generated by GPUBenchmark.jl Suite")
    end
end

function export_scaling_dat(scaling_results, run_dir)
    dat_file = joinpath(run_dir, "scaling.dat")
    open(dat_file, "w") do io
        println(io, "# GPUBenchmark Scaling Data")
        println(io, "# Algorithm: ", get(scaling_results, "algorithm", "unknown"))
        println(io, "# N\tMode\tID/Threads\tTime(s)\tTFLOPS")
        
        # CPU results
        cpu_res = get(scaling_results, "cpu_results", [])
        for res in cpu_res
            @printf(io, "%d\tCPU\t%d\t%.6f\t%.4f\n", 
                get(res, "n", 0), get(res, "threads", 0), get(res, "time_s", 0.0), get(res, "tflops", 0.0))
        end
        
        # GPU results
        gpu_res = get(scaling_results, "gpu_results", Dict())
        for (id, runs) in gpu_res
            for res in runs
                @printf(io, "%d\tGPU\t%d\t%.6f\t%.4f\n", 
                    get(res, "n", 0), id, get(res, "time_s", 0.0), get(res, "tflops", 0.0))
            end
        end
    end
end

end # module